### ISSUE TITLE
Add Google Books

### ISSUE THREAD

**Issue by macx** [PierBover/AlfredWorkflowGoogleApps#2]
I wanted to fork this repro in order to add Google Books, but didn't understand the uids you are using. Anyway: Could you please add [Google Books](https://play.google.com/books) (own books, not the store)?

![google-books](https://cloud.githubusercontent.com/assets/84112/15667441/874660a2-2716-11e6-9833-c0d4475807cd.png)

**Comment by PierBover** [comment]
Sure!

Give me a couple of hours.

**Comment by PierBover** [comment]
Sorry I completely forgot about this... I'll try to implement it in the following days.

**Comment by PierBover** [comment]
Sorry it took so long, but it's available now.
