### ISSUE TITLE
Multiple account support?

### ISSUE THREAD

**Issue by apowers313** [PierBover/AlfredWorkflowGoogleApps#3]
I have 9 different Google accounts (various jobs, domains, etc.) -- is there any way this could support multiple accounts? Happy to do some of the work if you think it would be possible.

**Comment by PierBover** [comment]
Hi

I've been thinking about this and it's quite complicated.

Right now the workflow only calls URLs on the default browser and AFAIK you can't switch Google accounts with a simple URL. If you can find a way to do that we could see the best way to implement it in the workflow.

Another possible solution would be to have an extension in your browser with your accounts configured which would receive a specifically formatted URL and in turn be able to receive an account and a Google service from Alfred and let the extension do the work.

**Comment by PierBover** [comment]
I will close this since it's not possible to solve this from the Alfred workflow.
